export default { 
    DATA_BASE_CONNECTION_ERROR : 1000,
    INVALID_ACCESS_TOKEN : 1001,
    ERROR_LOADING_DATA_FROM_DATABASE : 1002,
    ERROR_LOADING_DATA_FROM_EXTERNAL_SOURCE : 1003,
    ENABLE_TO_SAVE_RECORD_TO_DATA_BASE : 1004,
    ENABLE_TO_UPDATE_RECORD_IN_DATA_BASE: 1005 
}